JENKINS:
  git_global_user: GitTest
GIT:
  df_store_vkey: dfstore
LOG:
  log_location: /var/log/dynamic-pipeline/job_config_flo.log
  flo_name: job-config-flo

PIPE_LINE_DETAILS:
  continous_builder: continous_builder
  artifact_repo: artifact_repo
  infra_automation_tool: infra_automation_tool
  issue_tracker: issue_tracker
  database: database
  database_url: mongodb_connectionstring

VAULT:
  vault_url: https://vault-uat.company.com
  vault_path: dynamic-pipeline/local

ARTIFACT_REPO:
  artifact_repository: bot-dev

MAIL:
  MAIL_FROM: noreply-dynamic-pipeline-local@company.com
  JENKINS_MAIL_FROM: noreply-jenkins-local@company.com
  MAIL_SUPPORT:
    - nagaraju.meruva@company.com

